# Settings related to the crate i.e. things like previews
crate:
  # Preview related settings i.e. the look of the item.
  preview:
    # The name of the item.
    name: "<yellow>Do you have protection?"
    # The lore of the item.
    lore:
      - "<gradient:#8fcfa0:#32a852>I'm wearing my armor!"
    # The item material.
    item: "enchanted_book"
    # The list of enchantments.
    enchantments:
      - "protection:5"
      - "unbreaking:3"
    # The amount to display.
    amount: 1
    # Other preview settings.
    settings:
      # The item model, which replaces Custom Model Data indefinitely now.
      # This is much preferred over direct integration with plugins. It is less likely to break.
      # If you wish to disable this, set the fields to blank as they are by default.
      model:
        # The namespace i.e. nexo.
        namespace: ""
        # The id i.e. emerald_helmet.
        id: ""
  # Broadcast a message to the server.
  broadcast:
    # If the messages should be sent.
    enabled: false
    # The messages to broadcast.
    messages:
      - "<red>{player} won the prize <yellow>{reward} from {crate}."
    # If the player has this permission, they do not get the broadcast.
    permission: ""
  # Spawn fireworks, when a player wins this prize.
  firework:
    # Should fireworks spawn?
    enabled: false

# The items to win, when a prize is selected.
items:
  "1":
    # The item material.
    material: "enchanted_book"
    # The enchantments, to apply to the item.
    # All enchantments use vanilla identifiers, so  fire_aspect, bane_of_arthropods, luck, etc.
    enchantments:
      unbreaking: 3
      protection: 5
  "2":
    # Grabs an item, from items.json which is populated by /crates item <id> [value].
    # Often used for items that are hard to allow in configurations.
    key: "default"

# Commands to send, when a prize is selected.
commands:
  - "msg {player} <red>You won the prize <yellow>{reward}."

# Messages to send, when a prize is selected.
messages: []