package com.badbones69.crazycrates.api.files

import com.badbones69.crazycrates.CrazyCrates
import com.badbones69.crazycrates.utils.PluginUtils
import org.bukkit.configuration.file.FileConfiguration
import org.bukkit.configuration.file.YamlConfiguration
import java.io.File


object FileManager {

    private val homeFolders = arrayListOf<String>()
    private val customFiles = arrayListOf<CustomFile>()
    private val jarHomeFolders = hashMapOf<String, String>()
    private val autoGeneratedFiles = hashMapOf<String, String>()

    private val plugin = PluginUtils.plugin

    private var logInfo = false;

    fun setup(): FileManager {
        if (!plugin.dataFolder.exists()) plugin.dataFolder.mkdirs()

        if (isHomeFoldersEmpty()) {
            getHomeFolders().forEach { homeFolder ->
                val homeFile = File(plugin.dataFolder, "/$homeFolder")
                var folder = homeFolder

                if (homeFile.exists()) {
                    homeFile.list()?.forEach { name ->
                        if (name.endsWith(".yml")) {
                            val customFile = CustomFile(name, folder)

                            if (customFile.exists()) addCustomFile(customFile)
                        }
                    }

                    return this
                } else {
                    homeFile.mkdir()

                    val autoGenerated = getAutoGeneratedFiles()

                    autoGenerated.keys.forEach { fileName ->
                        if (autoGenerated[fileName].equals(folder, ignoreCase = true)) {
                            folder = autoGenerated[fileName].toString()

                            runCatching {
                                if (fileName.lowercase().endsWith(".yml")) customFiles.add(CustomFile(fileName, homeFolder))
                            }.onSuccess {
                                plugin.logger.info("Created default file: $folder/$fileName")
                            }.onFailure {
                                if (logInfo) {
                                    plugin.logger.warning("Could not save $fileName")

                                    it.printStackTrace()
                                }
                            }
                        }
                    }
                }
            }
        }

        return this
    }

    private fun isHomeFoldersEmpty() = homeFolders.size > 0

    private fun getHomeFolders() = homeFolders

    private fun getAutoGeneratedFiles() = autoGeneratedFiles

    private fun getOrDefault(fileName: String, folder: String) = jarHomeFolders.getOrDefault(fileName, folder)

    fun logInfo(toggle: Boolean) {
        this.logInfo = toggle
    }

    fun registerCustomFolder(homeFolder: String): FileManager {
        homeFolders.add(homeFolder)

        return this
    }

    fun unregisterCustomFolder(homeFolder: String): FileManager {
        homeFolders.remove(homeFolder)

        return this
    }

    fun registerDefaultGeneratedFiles(fileName: String, homeFolder: String): FileManager {
        autoGeneratedFiles[fileName] = homeFolder
        jarHomeFolders[fileName] = homeFolder

        return this
    }

    fun unregisterDefaultGeneratedFiles(fileName: String): FileManager {
        autoGeneratedFiles.remove(fileName)
        jarHomeFolders.remove(fileName)

        return this
    }

    private fun addCustomFile(customFile: CustomFile) {
        customFiles.add(customFile)

        plugin.logger.info("Loaded custom file: ${customFile.getHomeFolder()}/${customFile.getFileName()}!")
    }

    fun getCustom(name: String?): CustomFile? {
        for (file in customFiles) {
            if (file.getFileName().equals(name, ignoreCase = true)) {
                return file
            }
        }

        return null
    }

    fun saveCustom(fileName: String) {
        val customFile = getCustom(fileName) ?: return

        runCatching {
            customFile.getFile()?.save(File(plugin.dataFolder, "${customFile.getHomeFolder()}/${customFile.getFileName()}"))
        }.onFailure {
            plugin.logger.warning("Could not save ${customFile.getFileName()}!")

            it.printStackTrace()
        }.onSuccess {
            plugin.logger.info("Successfully saved ${customFile.getFileName()}.")
        }
    }

    fun reloadCustom(fileName: String) {
        val customFile = getCustom(fileName) ?: return

        runCatching {
            customFile.getFile = YamlConfiguration.loadConfiguration(File(plugin.dataFolder, "/${customFile.getHomeFolder()}/${customFile.getFileName()}"))
        }.onFailure {
            plugin.logger.warning("Could not reload ${customFile.getFileName()}!")

            it.printStackTrace()
        }.onSuccess {
            plugin.logger.info("Successfully reloaded ${customFile.getFileName()}.")
        }
    }

    fun getAllCratesNames(plugin: CrazyCrates): ArrayList<String>? {
        val files = ArrayList<String>()

        val crateDir = File(plugin.dataFolder, "/crates")

        crateDir.list()?.forEach {
            if (it.endsWith(".yml")) {
                files.add(it.replace(".yml".toRegex(), ""))
            }
        }

        return files
    }

    class CustomFile(private val fileName: String, private val homeFolder: String) {

        init {
            create()
        }

        private var file: FileConfiguration? = null

        private val blankFile: File? = null

        var getFile = file

        fun getFileName() = fileName

        fun getHomeFolder() = homeFolder

        fun getFile() = file

        fun exists() = file != null

        private val plugin = PluginUtils.plugin

        private fun create() {

            val newFile = File(plugin.dataFolder, "/$homeFolder/$fileName")

            runCatching {
                file = if (newFile.exists()) {
                    YamlConfiguration.loadConfiguration(newFile)
                } else {
                    null
                }
            }.onFailure {
                newFile.mkdir()

                plugin.logger.warning("Could not save ${newFile.name}!")

                plugin.logger.info("The folder $homeFolder/ was not found so it was made.")

                file = null
            }
        }

        fun save() {
            if (file == null) return

            runCatching {
                if (blankFile != null) file?.save(blankFile)
            }.onFailure {
                plugin.logger.warning("Could not save $fileName")

                it.printStackTrace()
            }.onSuccess {
                plugin.logger.finest("$fileName has been saved.")
            }
        }

        fun reload() {
            if (file == null) return

            runCatching {
                file = blankFile?.let { YamlConfiguration.loadConfiguration(it) }
            }.onFailure {
                plugin.logger.warning("Could not reload $fileName")

                it.printStackTrace()
            }.onSuccess {
                plugin.logger.finest("$fileName has been reloaded.")
            }
        }
    }
}